README.rst
This fixes the following error in `README.rst`:
changes `synth = servertools.Synth(synthdef)` to `synth = supriya.Synth(synthdef)`
The latter statement works with the current code in `HEAD master`. The former does not.
=> Fix error in README code

setup.py, supriya/__init__.py, supriya/realtime/Server.py, tests/test_realtime_Node__handle_response.py
Add optional `scsynth_path` keyword to `Server.boot()`, overriding `SCSYNTH_PATH` environment variable and any auto-detected `scsynth`. This allows for specific `scsynth` versions, or using `supernova`.
=> Allow specifying boot executable

supriya/scsynth.py, tests/nonrealtime/test_nonrealtime_Session_render.py, tests/test_scsynth.py
Following #170, I've [added two standard installation paths](https://github.com/deeuu/supriya/blob/find-scsynth/supriya/scsynth.py#L159-L163) to be included in the search for `scsynth` as performed by [`find`](https://github.com/deeuu/supriya/blob/find-scsynth/supriya/scsynth.py#L166) (see doc-string). Also included some tests at `tests/test_scsynth.py`.
Preferred to brute-force it over doing any clever OS logic.
@josiah-wolf-oberholtzer Let me know what you think
=> Include app paths when finding scsynth

supriya/_version.py, supriya/ugens/bases.py, supriya/ugens/triggers.py
22.9b0 broke SendReply's binary format.
Also remove the kw-only restriction on UGen parameters (for now!).
=> Hotfix SendReply

tests/providers/test_RealtimeProvider.py
As of now, supriya passes all test on my machine, except two in `tests/providers/test_RealtimeProvider.py`.
My setup is JACK on Linux, with 48000 sample rate and block size 512.
The two tests *always fail* on my machine if the waiting time 0.1s, and they *always pass* if waiting time is 0.2s.
This makeshift solution works well for me.
=> Increase waiting time for test_RealtimeProvider

supriya/nonrealtime/renderer.py, supriya/realtime/protocols.py, supriya/scsynth.py
When I execute this code on Windows:
```
import supriya
serv = supriya.Server()
opt = supriya.Options(input_device="ASIO : JackRouter")
serv.boot(options=opt)
```
I get the error message:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "D:\tmp\supriya\supriya\realtime\servers.py", line 1041, in boot
self._process_protocol.boot(self._options, scsynth_path, port)
File "D:\tmp\supriya\supriya\realtime\protocols.py", line 69, in boot
raise supriya.exceptions.ServerCannotBoot(line)
supriya.exceptions.ServerCannotBoot: ERROR: Invalid option JackRouter
```
Apparently, Supriya doesn't escape white spaces in the device name. 
My solution is to put quotation marks \" \" around the device name, but then the device name is `.spit()` anyways in …
=> Serialize server command line options

supriya/providers.py, supriya/realtime/nodes.py, supriya/realtime/servers.py, tests/providers/test_RealtimeProvider.py, tests/realtime/test_Group.py
...to allow allocation of parallel groups on supernova.
Ref.: #https://github.com/gitmarek/supriya/commit/cef6ef88d10d5571a038a7bdc1eb2e2ad3b29f78#r87738788
Locally, all tests passed, so it looks like I didn't break anything. Before squashing anything, I'm going to test it manually and wait for supernova to be deployed on GHA to try to write some unit tests too...
=> Add parallel=False flag to Group()

supriya/osc/messages.py, tests/osc/test_osc_OscMessage.py
Prepare for 8 Feb 2036.
Ref.: https://github.com/gitmarek/supriya/pull/14
See also: https://www.eecis.udel.edu/~mills/y2k.html
=> Check for NTP timestamp oveflow

supriya/realtime/allocators.py, tests/realtime/test_BlockAllocator.py
When trying to allocate a block within an already allocated block with `BlockAllocator()` (Hypothesis wants to do it all the time...) Supriya fails on its internal assertion. See 4b75572e5393f144de93534799bfe769b214a615 for how to trigger this.
A solution could be to test for empty `starting_blocks` in `BlockAllocator.allocate_at()`.
=> Pass BlockAllocator.allocate_at() assertion

supriya/realtime/servers.py, supriya/scsynth.py
Audio bus, control bus, buffer and sync ID allocators should create separate ID arenas per client ID.
Fixes #304
=> Allocators take client ID into account

.github/workflows/test.yml, conftest.py, docs/source/conf.py, pyproject.toml, supriya/contexts/__init__.py, supriya/contexts/core.py, supriya/contexts/entities.py, supriya/contexts/errors.py, supriya/contexts/nonrealtime.py, supriya/contexts/realtime.py, supriya/contexts/requests.py, supriya/contexts/responses.py, supriya/enums.py, supriya/ext/book.py, supriya/querytree.py, supriya/scsynth.py, supriya/typing.py, tests/contexts/conftest.py, tests/contexts/test_Score_buffers.py, tests/contexts/test_Score_buses.py, tests/contexts/test_Score_nodes.py, tests/contexts/test_Score_render.py, tests/contexts/test_Score_synthdefs.py, tests/contexts/test_Server_buffers.py, tests/contexts/test_Server_buses.py, tests/contexts/test_Server_lifecycle.py, tests/contexts/test_Server_misc.py, tests/contexts/test_Server_nodes.py, tests/contexts/test_Server_synthdefs.py
This PR:
- Completely reimplements Supriya's interaction with scsynth
- Completely harmonizes realtime and non-realtime interaction with scsynth via a common Context class and a set of context objects common to both realtime and non-realtime synthesis
- Takes patterns established by Provider and fuses those patterns into the new core
- Exposes far more methods for interacting with scsynth than ever before
- Makes creating "completions" for various server interactions easy via context managers
=> Unified contexts

supriya/__init__.py, supriya/contexts/core.py, supriya/contexts/entities.py, supriya/contexts/requests.py, supriya/synthdefs/builders.py, tests/contexts/test_Score_nodes.py, tests/contexts/test_Server_nodes.py
=> Implement setting node controls by index and range

supriya/assets/synthdefs/__init__.py, supriya/assets/synthdefs/test.py, supriya/contexts/core.py, supriya/contexts/requests.py, tests/contexts/test_Score_nodes.py, tests/contexts/test_Server_nodes.py
This enables passing tuples of floats to `Group.add_synth`. For example:
```
@synthdef()
def test_synth(freq=(220, 440)):
sig = SinOsc.ar(frequency=freq) * 0.5
sig = Mix.new(sig)
Out.ar(bus=0, source=[sig, sig])
_ = server.add_synthdefs(test_synth)
server.sync()
group.add_synth(test_synth, freq=(220.0, 330))
```
=> Allow passing tuples of floats to `def add_synth`

supriya/__init__.py, supriya/_version.py, supriya/contexts/realtime.py
In response to https://github.com/josiah-wolf-oberholtzer/supriya/discussions/347 let's issue warnings when the client receives `/fail` responses from the server.
```
>>> from supriya import Server
>>> from supriya.patterns import EventPattern, ParallelPattern, SequencePattern
>>>
>>> server = Server().boot()
>>> pattern = ParallelPattern([
...     EventPattern(
...         frequency=SequencePattern([440, 550]),
...     ),
...     EventPattern(
...         frequency=SequencePattern([1500, 1600, 1700]),
...         delta=0.75,
...     ),
... ])
>>> player = pattern.play(context=server)
>>> /Users/josiah/Source/github.com/josiah-wolf-oberholtzer/supriya/supriya/contexts/realtime.py:210: FailWarning: /s_new SynthDef not found
warnings.warn(" ".join(str(x) for x in message.contents), …
```
=> Warn on /fail responses

supriya/enums.py, supriya/ugens/bases.py
=> SUPRIYA-352: Add UGen Bitwise Operators

.github/actions/supercollider/action.yml, .github/workflows/test.yml, tests/contexts/test_Server_misc.py
GHA's jack has been cranky without installing additional audio devices.
I attempted to fix this by installing BlackHole, but per https://github.com/ExistentialAudio/BlackHole/discussions/638#discussioncomment-9101745 HomeBrew's version of BlackHole is out-of-date.
Edit: Just seems like jack fails to create the null audio device randomly on OSX. We can just re-run those tests until they work 🤷‍♀️
=> Pin SuperCollider to 3.13

.github/workflows/test.yml
SuperCollider is currently failing to build on macOS. Let's skip so other PRs can go green while we figure out what's wrong.
=> Skip macOS builds

supriya/ugens/core.py
Let's simplify the `UGenOperable` method names, bringing them closer inline with Python's own `math` module and (where appropriate) with `sclang`.
Name changes:
```
absolute_difference -> absdiff
as_int              -> digit_value
as_maximum          -> max
as_minimum          -> min
ceiling             -> __ceil__
exponential_range   -> scale
floor               -> __floor__
power               -> __pow__
range               -> scale 
square_root         -> sqrt
```
=> Rename UGenOperable methods

.github/workflows/test.yml, pyproject.toml, tests/book/test_ext_book.py
I'm tired...
- of not being able to subscript classes for type annotations
- of needing to use `Optional` everywhere instead of `type | None`
- of needing to use Dict, List, Set instead of dict, list, set
I'll have to wait for `type | None` until we get to 3.10, but we can knock the others out.
=> Drop support for Python 3.8

supriya/contexts/realtime.py, supriya/osc/asynchronous.py, supriya/osc/protocols.py, supriya/osc/threaded.py, tests/contexts/test_Server_lifecycle.py
Use a single dedicated function for managing the lifecycle of a server (sync or async), with the control flow in that function managed entirely by futures.
This guarantees that lifecycle event callbacks _only_ execute inside that single lifecycle management function, allowing for async callbacks to be executed _in order_ without needing to resort to spawning new tasks.
This also generally simplifies the server implementation(s), drastically reducing the complexity of callbacks between server, OSC protocol and process prototol.
=> Refactor server lifecycle management

supriya/osc/asynchronous.py, supriya/scsynth.py
Protocol callbacks are synchronous. If you need to orchestrate async code with them, use them to set futures / events.
=> Protocols do not support async callbacks

supriya/clocks/asynchronous.py, supriya/clocks/bases.py, supriya/clocks/offline.py, supriya/clocks/threaded.py, tests/clocks/test_AsyncClock.py, tests/clocks/test_Clock.py
The following methods shouldn't be part of the public interface:
- `get_current_time()` -> `_get_current_time()`
- `peek()` -> `_peek()`
- `quantization_to_beats()` -> `_quantization_to_beats()`
=> Make some Clock methods private

supriya/clocks/asynchronous.py, supriya/clocks/core.py, supriya/clocks/offline.py, supriya/clocks/threaded.py
A utility for entering a context, letting user code queue-up patterns, then running the offline clock once the context exits.
=> Add (Async)?OfflineClock.at() context manager

supriya/contexts/realtime.py
Without a sleep, BaseServer.dump_tree() doesn't catch all output on Windows, even when syncing. Not entirely sure why this is, but a little sleeping helps.
=> BaseServer.dump_tree() sleeps on Windows

supriya/osc/utils.py, supriya/patterns/events.py, tests/patterns/test_PatternPlayer.py
This PR adds a new NoteEvent.rest property which treats the performance of the note as a silence. Works with notes generated by both EventPattern and MonoEventPattern.
For example:
```
MonoEventPattern(
frequency=SequencePattern([444, 555, 666, 777]),
rest=SequencePattern([False, False, True, False]),
)
```
=> Implement NoteEvent.rest for resting
