supriya-project/supriya

requirements.txt, setup.py, supriya/tools/nonrealtimetools/Session.py, tox.ini
=> Modernize tox.ini.

supriya/tools/ugentools/Pulse.py, supriya/tools/ugentools/TwoZero.py, supriya/tools/ugentools/VOsc.py, supriya/tools/ugentools/VOsc3.py, supriya/tools/ugentools/Vibrato.py, supriya/tools/ugentools/XFade2.py
Pulse, XFade2, VOsc, VOsc3, and Vibrato.
=> Implemented 5 more UGens

requirements.txt, setup.py, tox.ini
=> Pin Abjad dependency to 2.19.

supriya/tools/responsetools/QueryTreeGroup.py, supriya/tools/responsetools/QueryTreeResponse.py, supriya/tools/responsetools/QueryTreeSynth.py, supriya/tools/responsetools/StatusResponse.py, supriya/tools/servertools/Server.py, supriya/tools/servertools/ServerMeters.py, supriya/tools/synthdeftools/SynthDef.py
SSIA.
This facilitates https://github.com/delucis/web-gui.
=> Implemented various .to_dict() methods.

supriya/__init__.py, supriya/docs/source/installation.rst, supriya/synthdefs/default.py, supriya/tools/nonrealtimetools/Session.py, supriya/tools/patterntools/test/test_Pbus.py, supriya/tools/patterntools/test/test_Pbus_Pgpar.py, supriya/tools/patterntools/test/test_Ppar.py, supriya/tools/synthdeftools/SynthDef.py, supriya/tools/synthdeftools/SynthDefDecompiler.py, supriya/tools/synthdeftools/SynthDefFactory.py, supriya/tools/synthdeftools/UGenMethodMixin.py, supriya/tools/synthdeftools/test/test_SynthDefFactory.py, supriya/tools/synthdeftools/test/test_SynthDef___str__.py, supriya/tools/ugentools/Control.py, supriya/tools/ugentools/UGen.py, supriya/tools/ugentools/Warp1.py, supriya/tools/ugentools/XFade2.py
=> Implement SynthDefFactory

.travis.yml, Makefile, conftest.py, supriya/osc/OscIO.py, supriya/realtime/Server.py, tests/conftest.py, tests/test_realtime_Server_boot.py
Adds tests for server timeouts and server address-in-use errors. Fixes #140.
=> Test scsynth error handling

supriya/ext/ipython.py
Use LAME to compress audio in IPython notebooks (if possible) for drastically smaller file sizes.
=> IPython MP3 Audio

.github/actions/supercollider/action.yml, .github/workflows/testing.yml, supriya/utils.py
Split SuperCollider build into own composite action.
=> Refactor GHA

supriya/enums.py, supriya/synthdefs/__init__.py, supriya/synthdefs/builders.py, supriya/synthdefs/envelopes.py
Inspired by a conversation at https://scsynth.org/t/sc3-vs-supriya-as-python-scsynth-front-ends/5140/4
=> Implement synthdef decorator, Envelope.adsr()

setup.py
I reimplemented sphinx-copybutton behavior in https://github.com/josiah-wolf-oberholtzer/sphinx-immaterial
Let's use the repo until if/when mainline implements something equivalent.
=> Use custom sphinx-immaterial

.github/actions/supercollider/action.yml, .github/workflows/test.yml, setup.py, supriya/_version.py, supriya/clocks/bases.py, supriya/commands/__init__.py, supriya/commands/bases.py, supriya/commands/synths.py, supriya/nonrealtime/renderer.py, supriya/osc/messages.py, supriya/patterns/players.py, supriya/realtime/buses.py, supriya/realtime/nodes.py, supriya/scsynth.py, supriya/typing.py, tests/providers/test_RealtimeProvider.py
=> Add Python 3.7 support

supriya/nonrealtime/renderer.py, supriya/nonrealtime/sessions.py, tests/nonrealtime/test_nonrealtime_Session_render.py
Session rendering now uses asyncio internally for each call to scsynth.
=> Add Session.render_async()

supriya/ext/mypy.py
Treat rate methods for UGens with (potentially) > 1 output as `UGenArray` rather than `UGenMethodMixin`
=> Extend mypy plugin

.github/workflows/test.yml, supriya/ext/__init__.py, supriya/ext/book.py, supriya/io.py, supriya/nonrealtime/sessions.py, supriya/realtime/buffers.py, supriya/soundfiles.py, tests/book/test_ext_book.py
=> Cleanup audio rendering in Sphinx

supriya/nonrealtime/buffers.py, supriya/nonrealtime/sessions.py, supriya/providers.py, tests/providers/test_NonrealtimeProvider.py, tests/providers/test_RealtimeProvider.py
Implement:
- .close()
- .normalize()
- .read()
- .write()
=> Implement missing Provider buffer methods

supriya/ugens/bases.py, tests/synthdefs/test_synthdefs_SynthDefCompiler_splay.py
=> SUPRIYA-351: Fix BinaryOpUGen shortcut

pyproject.toml
=> SUPRIYA-355: Fix invalid cross-device link

supriya/scsynth.py, tests/test_scsynth.py
Fixes #409 
Python logic should match https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Control/Server.sc#L189-L198
=> SUPRIYA-409: Fix hardware device options

.github/workflows/test.yml, pyproject.toml
=> Drop support for Python 3.9

pyproject.toml
=> Unpin Sphinx

supriya/__init__.py, supriya/clocks/__init__.py, supriya/contexts/__init__.py, supriya/contexts/core.py, supriya/contexts/nonrealtime.py, supriya/contexts/realtime.py, supriya/enums.py, supriya/osc/asynchronous.py, supriya/osc/protocols.py, supriya/patterns/players.py, supriya/typing.py, tests/contexts/test_Server_lifecycle.py, tests/contexts/test_Server_misc.py
=> Implement Lifecycle Callbacks

supriya/contexts/allocators.py, supriya/contexts/nonrealtime.py, supriya/ext/mypy.py, supriya/ugens/core.py, supriya/ugens/envelopes.py, supriya/ugens/factories.py, supriya/ugens/lines.py, supriya/ugens/pv.py, supriya/utils/_intervals.pyx, supriya/utils/intervals.py
=> Replace asserts with explicit exceptions

supriya/patterns/patterns.py, supriya/patterns/players.py, tests/patterns/test_PatternPlayer.py
=> Pattern.play() doesn't start clocks

Makefile, examples/hello_world/README.md, examples/hello_world/hello_world.py
Let's add a "hello, world!" example demonstrating playing a chord via Supriya's different realtime/non-realtime paradigms
=> Add "hello, world!" example

docs/source/buses.rst, supriya/contexts/core.py, supriya/contexts/entities.py, supriya/patterns/events.py, tests/contexts/test_Score_nodes.py, tests/contexts/test_Server_nodes.py, tests/patterns/test_NoteEvent.py, tests/patterns/test_PatternPlayer.py
=> Busses no longer auto-map with add_synth

supriya/ugens/envelopes.py
=> Implement Envelope.to_array()

supriya/contexts/realtime.py, supriya/contexts/scopes.py, tests/contexts/test_Scope.py
=> Implement Scope classes

supriya/osc/protocols.py, tests/contexts/test_Server_buffers.py, tests/contexts/test_Server_buses.py, tests/contexts/test_Server_misc.py, tests/contexts/test_Server_nodes.py, tests/contexts/test_Server_synthdefs.py, tests/test_examples.py
- Capture.filtered() returns list[CaptureEntry]
- Capture.filtered(status=False) is now the default
=> Refactor Capture.filtered()
